#FROM openjdk:8-jdk-alpine

FROM openjdk:17-alpine3.14
#ARG DEPENDENCY=target/dependency
#
#COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
#COPY ${DEPENDENCY}/META-INF /app/META-INF
#COPY ${DEPENDENCY}/BOOT-INF/classes /app
#
#ENTRYPOINT ["java","-cp","app:app/lib/*",
#"com.in28minutes.rest.webservices.restfulwebservices.RestfulWebServicesApplication"]


#docker build -t nabilnader/hello-api:latest .

# docker run -p 8080:8080 nabilnader/hello-api:latest

#com.in28minutes.rest.webservices.restfulwebservices.RestfulWebServicesApplication ,
#this is our main entity point for spring